name: Unity Catalog (UC) Catalog Request
description: Create UC Catalog Request Form
labels: [Catalogs]

title: "Catalogs"

body:

- type: dropdown
  id: environment
  attributes:
    label: Select Environment
    options:
      - unity_catalog
  validations:
    required: True

- type: dropdown
  id: create_or_delete
  attributes:
    label: Select to 'create' or 'destroy' Resource
    options:
      - create
      - destroy
  validations:
    required: True

- type: input
  id: resource_name
  attributes:
    description: "Please note: 'underscores' or 'dashes' can be used in the name."
    label: Please Enter the UC Catalog Name
  validations:
    required: True

- type: input
  id: catalog_principal_name
  attributes:
    label: Please Enter the Principal or Group Name for Catalog Access
  validations:
    required: True

- type: checkboxes
  id: catalog_principal_privileges
  attributes:
    label: Please Select the Grants for the Principal or Group Name
    description: "Please note: If selecting 'ALL_PRIVILEGES', ensure no other boxes are checked."
    options:
      - label: USE CATALOG
        required: False
      - label: USE SCHEMA
        required: False
      - label: APPLY_TAG
        required: False
      - label: EXECUTE
        required: False
      - label: MODIFY
        required: False
      - label: READ_VOLUME
        required: False
      - label: REFRESH
        required: False
      - label: SELECT
        required: False
      - label: WRITE_VOLUME
        required: False
      - label: CREATE_FUNCTION
        required: False
      - label: CREATE_MATERIALIZED_VIEW
        required: False
      - label: CREATE_MODEL
        required: False
      - label: CREATE_SCHEMA
        required: False
      - label: CREATE_TABLE
        required: False
      - label: CREATE_VOLUME
        required: False
      - label: ALL_PRIVILEGES
        required: False
  validations:
    required: True