name: Workspace Cluster Policy Request
description: Create Workspace Cluster Policy Request Form
labels: [cluster policy]

title: "Cluster Policy"

body:

- type: input
  id: gh_branch_name
  attributes:
    label: Please Enter the Github Feature Branch Name
  validations:
    required: True

- type: dropdown
  id: environment
  attributes:
    label: Select Environment
    options:
      - dev
      - prod
  validations:
    required: True

- type: dropdown
  id: create_or_delete
  attributes:
    label: Select to 'Create' or 'Destroy' Resource
    options:
      - Create
      - Destroy
  validations:
    required: True

- type: input
  id: resource_name
  attributes:
    description: "Please note: 'underscores' or 'dashes' can be used in the name."
    label: Please Enter the Cluster Policy Name
  validations:
    required: True

- type: dropdown
  id: cluster_profile
  attributes:
    label: Please Select the Cluster Profile
    options: 
      - singleNode
  validations:
    required: True

- type: dropdown
  id: cluster_type
  attributes:
    label: Please Select the Cluster Type
    options: 
      - all-purpose
  validations:
    required: True

- type: dropdown
  id: runtime_engine
  attributes:
    label: Please Select the Runtime Engine
    options: 
      - STANDARD
  validations:
    required: True

- type: checkboxes
  id: nodetype_id
  attributes:
    label: Please Select the Node Type IDs
    options:
      - label: i3.xlarge
        required: False
      - label: i3.2xlarge
        required: False
  validations:
    required: True

- type: dropdown
  id: spark_version
  attributes:
    label: Please Select the Spark Version
    options: 
      - auto:latest-ml
  validations:
    required: True

- type: input
  id: num_workers
  attributes:
    label: Please Enter the Number of Workers
  validations:
    required: True

- type: input
  id: min_workers
  attributes:
    label: Please Enter Min Workers
  validations:
    required: True

- type: input
  id: max_workers
  attributes:
    label: Please Enter Max Workers
  validations:
    required: True

- type: dropdown
  id: auto_termination_mins
  attributes:
    label: Please Select Auto Termination Minutes
    options: 
      - 30
      - 60
      - 90
      - 120
  validations:
    required: True

- type: input
  id: cluster_policy_principal_name
  attributes:
    label: Please Enter the Principal or Group Name for Cluster Policy Use Permissions
  validations:
    required: True

- type: dropdown
  id: cluster_policy_principal_privileges
  attributes:
    label: Please Select the Grants for the Principal or Group Name
    options:
      - CAN_USE
  validations:
    required: True
