name: Delta Shares Request
description: Create Delta Shares Request Form
labels: [Delta Shares]

title: "Delta Shares"

body:

- type: dropdown
  id: environment
  attributes:
    label: Select Environment
    options:
      - dev
      - prod
  validations:
    required: True

- type: dropdown
  id: create_or_delete
  attributes:
    label: Select to 'create' or 'destroy' Resource
    options:
      - create
      - destroy
  validations:
    required: True

# - type: input
#   id: ds_metastore_id
#   attributes:
#     description: "The metastore id can be found in the Databricks admin account console."
#     label: Please Enter the Databricks Workspace Metastore ID
#   validations:
#     required: True

- type: input
  id: resource_name
  attributes:
    description: "Please note: only 'dashes' are allowed in the delta share name."
    label: Please Enter the Delta Share Name
  validations:
    required: True

# - type: input
#   id: ds_recipient_name_external
#   attributes:
#     label: Please Enter the Delta Share EXTERNAL Recipient Name (optional)
#     description: "Please note: only 'dashes' are allowed in the recipient name."
#   validations:
#     required: False

# - type: input
#   id: ds_recipient_name_databricks
#   attributes:
#     label: Please Enter the Delta Share DATABRICKS Recipient Name (optional)
#     description: "Please note: only 'dashes' are allowed in the recipient name."
#   validations:
#     required: False

# - type: input
#   id: ds_recipient_sharing_identifier
#   attributes:
#     label: Please Enter the Delta Share Recipient Sharing Identifier For the DATABRICKS Recipient Name (optional)
#     description: "Please note: this is only for Databricks to Databricks sharing (e.g. cloud:region:guid)"
#   validations:
#     required: False