name: Unity Catalog (UC) Schema Request
description: Create UC Schema Request Form
labels: [Schemas]

title: "Schemas"

body:

- type: dropdown
  id: environment
  attributes:
    label: Select Environment
    options:
      - unity_catalog
  validations:
    required: True

- type: dropdown
  id: create_or_delete
  attributes:
    label: Select to 'create' or 'destroy' Resource
    options:
      - create
      - destroy
  validations:
    required: True

- type: input
  id: resource_name
  attributes:
    description: "Please note: 'underscores' or 'dashes' can be used in the name."
    label: Please Enter the Schema Name
  validations:
    required: True

- type: input
  id: catalog_name
  attributes:
    description: "Please note: 'underscores' or 'dashes' can be used in the name."
    label: Please Enter the Catalog Name to Put Schema Under
  validations:
    required: True

- type: input
  id: catalog_principal_name
  attributes:
    label: Please Enter the 'Catalog' Service Principal Name for Catalog Access
  validations:
    required: True

- type: checkboxes
  id: catalog_principal_privileges
  attributes:
    label: Please Select the Grants for the 'Catalog' Principal Name
    description: "Please note: If selecting 'ALL_PRIVILEGES', ensure no other boxes are checked."
    options:
      - label: USE_CATALOG
      - label: USE_SCHEMA
  validations:
    required: True

- type: input
  id: schema_principal_name
  attributes:
    label: Please Enter the 'Schema' Principal or Group Name for Schema Access
  validations:
    required: True

- type: checkboxes
  id: schema_principal_privileges
  attributes:
    label: Please Select the Grants for the 'Schema' Principal or Group Name
    description: "Please note: If selecting 'ALL_PRIVILEGES', ensure no other boxes are checked."
    options:
      - label: USE_SCHEMA
      - label: APPLY_TAG
      - label: EXECUTE
      - label: MODIFY
      - label: READ_VOLUME
      - label: REFRESH
      - label: SELECT
      - label: WRITE_VOLUME
      - label: CREATE_FUNCTION
      - label: CREATE_MATERIALIZED_VIEW
      - label: CREATE_MODEL
      - label: CREATE_TABLE
      - label: CREATE_VOLUME
  validations:
    required: True