name: Unity Catalog Storage Credential Request
description: Create UC Storage Credential Request Form
labels: [Storage Credentials]

title: "Storage Credentials"

body:

- type: dropdown
  id: environment
  attributes:
    label: Select Environment
    options:
      - dev
      - prod
  validations:
    required: True

- type: dropdown
  id: create_or_delete
  attributes:
    label: Select to 'create' or 'destroy' Resource
    options:
      - create
      - destroy
  validations:
    required: True

- type: input
  id: resource_name
  attributes:
    description: "Please note: 'underscores' or 'dashes' can be used in the name."
    label: Please Enter the Storage Credential (SC) Name
  validations:
    required: True

- type: input
  id: sc_role_arn
  attributes:
    label: Please Enter the Integrated Access Management (IAM) Role AWS ARN
    placeholder: "Example: arn:aws:iam::111111111111:role/Temp-Product-IAM-Role_1111111111111"
  validations:
    required: True

- type: input
  id: sc_principal_name
  attributes:
    label: Please Enter the Principal or Group Name for Storage Credential Access
  validations:
    required: True

- type: checkboxes
  id: sc_principal_privileges
  attributes:
    label: Please Select the Grants for the Principal or Group Name
    description: "Please note: If selecting 'ALL_PRIVILEGES', ensure no other boxes are checked."
    options:
      - label: CREATE_EXTERNAL_TABLE
        required: False
      - label: CREATE_EXTERNAL_VOLUME
        required: False
      - label: CREATE_MANAGED_STORAGE
        required: False
      - label: READ_FILES
        required: False
      - label: WRITE_FILES
        required: False
      - label: ALL_PRIVILEGES
        required: False
  validations:
    required: True