export ENVIRONMENT=dev
export ISSUE_BRANCH_NAME=issue-216-branch
export ISSUE_CREATE_DESTROY=destroy
export MASTER_CONFIG_JSON_FNAME=catalogs.json
export GITHUB_ISSUE_NUMBER=216
export GITHUB_REPO_OWNER=robert-altmiller
export GITHUB_REPO_NAME=terraform_template_config
export GITHUB_REPO_URL=https://github.com/robert-altmiller/terraform_template_config.git
