export ENVIRONMENT=unity_catalog
export ISSUE_BRANCH_NAME=issue-415-branch
export ISSUE_CREATE_DESTROY=create
export MASTER_CONFIG_JSON_FNAME=catalogs.json
export GITHUB_ISSUE_NUMBER=415
export GITHUB_REPO_OWNER=robert-altmiller
export GITHUB_REPO_NAME=terraform_template_config
export GITHUB_REPO_URL=https://github.com/robert-altmiller/terraform_template_config.git
