export ENVIRONMENT=dev
export ISSUE_BRANCH_NAME=feature1
export ISSUE_CREATE_DESTROY=Destroy
export MASTER_CONFIG_JSON_FNAME=storage_credentials.json
export GITHUB_ISSUE_NUMBER=157
export GITHUB_REPO_OWNER=robert-altmiller
export GITHUB_REPO_NAME=terraform_template_config
export GITHUB_REPO_URL=https://github.com/robert-altmiller/terraform_template_config.git
