 
      - name: Trigger workflow in another repo
        run: |
          curl -X POST \
           -H "Authorization: token YOUR_PERSONAL_ACCESS_TOKEN" \
           -H "Accept: application/vnd.github.everest-preview+json" \
           "https://api.github.com/repos/USERNAME/REPO_NAME/dispatches" \
           -d '{"event_type": "run-workflow", "client_payload": { "workflow_name": "TARGET_WORKFLOW_NAME"}}'