name: Upload Artifact

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create a sample file
        run: echo "This is a sample file" > sample.txt

      - name: Upload sample.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: sample.txt