name: Download and Use Artifact

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  download-and-use-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
    
      - name: Downlod Artifacts 
        uses: actions/download-artifact@v3
    
      - name: List Files
        run: ls -R
