name: Download and Use Artifact

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  download-and-use-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download my-artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .

      - name: Display the content of the artifact
        run: cat sample.txt
