name: Fix Terraform PR Merge Issues

on:
  issue_comment:
    types: [created, edited]


jobs:

  fix_terraform_merge_pr_issue:
  
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'fix pr')

    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 # This is important to fetch all branches
      
  
      - name: Get PR details
        id: get-pr
        run: |
          FEATURE_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "${{ github.event.issue.pull_request.url }}" | jq -r .head.ref)
          echo FEATURE_BRANCH: $FEATURE_BRANCH
          echo "FEATURE_BRANCH=$FEATURE_BRANCH" >> $GITHUB_ENV
        shell: bash


      - name: Favor non-empty conflicts during merge
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Configure custom merge driver
          chmod +x ./shell_scripts/nonemptymerge.sh
          git config merge.nonemptymerge.name "favor non-empty content over empty content"
          git config merge.nonemptymerge.driver "./shell_scripts/nonemptymerge.sh %O %A %B %P"
          
          git fetch origin
          git checkout "$FEATURE_BRANCH"
          
          # Try to merge
          git merge origin/main
          
          # Push the changes
          git push origin "$FEATURE_BRANCH"
        shell: bash