name: Fix Terraform PR Merge Issues

on:
  issue_comment:
    types: [created, edited]


jobs:

  fix_terraform_merge_pr_issue:
  
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'fix pr')

    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 # This is important to fetch all branches
      
  
      - name: Merge dev into feature branch
        run: |
          git fetch origin
          git checkout "${{ github.event.pull_request.head.ref }}"
          git merge origin/dev
          git push origin "${{ github.event.pull_request.head.ref }}"


