name: Fix Terraform PR Merge Issues

on:
  pull_request_review_comment:
    types: [created]


jobs:

  fix_terraform_merge_pr_issue:
    
    runs-on: ubuntu-latest

    env:
      ISSUE_TITLE: "${{ github.event.issue.labels[0].name }}"

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 # This is important to fetch all branches
      
  
      - name: Merge dev into feature branch
        run: |
          git fetch origin
          git checkout "${{ github.event.pull_request.head.ref }}"
          git merge origin/dev
          git push origin "${{ github.event.pull_request.head.ref }}"


