name: Start Terraform Template Repo Composite Action to Deploy Infrastructure

on:
  pull_request:
    types:
      - closed

jobs:
  start_terraform_template_repo_composite_action:
    
    runs-on: ubuntu-latest

    steps:

      - name: Check for Specific Comments
        id: check_comments
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          ISSUE_BRANCH_NAME_MAIN=$(echo "$PR_BODY" | grep -oP 'Pull Request Feature Main Branch: \K[^ ]+')
          echo "ISSUE_BRANCH_NAME_MAIN: $ISSUE_BRANCH_NAME_MAIN"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Download File from S3
        run: |
          aws s3 cp s3://dbx-artifacts-bucket/composite_actions_env_vars/composite_action_env_vars.sh composite_action_env_vars.sh


      - name: Set Environment Variables from Artifact
        run: |
          source ./composite_action_env_vars.sh
          echo "ISSUE_BRANCH_NAME_MAIN: $ISSUE_BRANCH_NAME_MAIN"
          echo "ISSUE_BRANCH_NAME_MAIN=$ISSUE_BRANCH_NAME_MAIN" >> $GITHUB_ENV


      - uses: robert-altmiller/terraform_template@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_REGION:  ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
          DATABRICKS_ADMIN_LOGIN: ${{ secrets.DATABRICKS_ADMIN_LOGIN }}
          DATABRICKS_ADMIN_PASSWORD: ${{ secrets.DATABRICKS_ADMIN_PASSWORD }}
          DATABRICKS_CLIENT_ID_DEV: ${{ secrets.DATABRICKS_CLIENT_ID_DEV }}
          DATABRICKS_CLIENT_ID_PROD: ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}
          DATABRICKS_CLIENT_ID_SECRET_DEV: ${{ secrets.DATABRICKS_CLIENT_ID_SECRET_DEV }}
          DATABRICKS_CLIENT_ID_SECRET_PROD: ${{ secrets.DATABRICKS_CLIENT_ID_SECRET_PROD }}
          DATABRICKS_INSTANCE_DEV: ${{ secrets.DATABRICKS_INSTANCE_DEV }}
          DATABRICKS_INSTANCE_PROD: ${{ secrets.DATABRICKS_INSTANCE_PROD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_BRANCH_NAME_MAIN: ${{ env.ISSUE_BRANCH_NAME_MAIN }}