name: Start Terraform Template Repo Composite Action to Deploy Infrastructure

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  start_terraform_template_repo_composite_action:
    runs-on: ubuntu-latest

    steps:
    - uses: robert-altmiller/terraform_template@main
      with:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
