name: Process Storage Credential Request

on:
  issues:
    types: [opened]

jobs:
  get_issue_in_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install jq
        run: sudo apt-get install jq

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/storage-credential-request.yml

      - name: Output issue parser Json results 
        run: cat ${HOME}/issue-parser-result.json

      - name: Checkout Target Repo
        uses: actions/checkout@v2
        with:
          repository: 'robert-altmiller/terraform_template'
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Write submission issue Json to Json file
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue_submission/issue_submission.json

      - name: Commit Json issue file to target Terraform repo
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/robert-altmiller/terraform_template.git
          git pull && \
          git add issue_submission/issue_submission.json && \
          git commit -m 'new infrastructure submission' && \
          git push


